default: &default
  adapter: postgresql
  encoding: unicode
  username: angelosathanasiosmakris
  password:
  host: localhost

development:
  adapter: postgresql
  encoding: unicode
  database: skipper_development
  pool: 5
  username: angelosathanasiosmakris
  password: <%= ENV['DATABASE_PASSWORD'] %>
  host: localhost

production:
  adapter: postgresql
  encoding: unicode
  database: skipper-database
  pool: 5
  username: <%= ENV['DATABASE_USERNAME'] %>
  password: <%= ENV['DATABASE_PASSWORD'] %>
  host: <%= ENV['DATABASE_HOST'] %>
