default: &default
  adapter: postgresql
  encoding: unicode
  username: angelosathanasiosmakris
  password:
  host: localhost

development:
  <<: *default
  database: skipper_development

test:
  <<: *default
  database: skipper_test

production:
  url: <%= ENV['DATABASE_URL'] %>
  pool: 5
  timeout: 5000
