default: &default
  adapter: postgresql
  encoding: unicode
  username: angelosathanasiosmakris
  password:
  host: localhost

development:
  <<: *default
  database: skipper_development

test:
  <<: *default
  database: skipper_test

production:
  <<: *default
  database: skipper_production
  username: <%= ENV["DATABASE_USERNAME"] %>
  password: <%= ENV["DATABASE_PASSWORD"] %>
